name: E2E test

env:
  NODE_VERSION: "20"

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
      - code-improvement # todo remove before merging into develop
jobs:
  cypress:
    name: ${{ matrix.core.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}

    steps:
    - name: "Install node v${{ env.NODE_VERSION }}"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Composer (optional)
      run: composer install
      continue-on-error: true

    - name: Build (optional)
      run: npm run build
      continue-on-error: true

    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Test
      run: npm run cypress:run
      env:
        BRIGHTCOVE_ACCOUNT_ID: ${{ secrets.BRIGHTCOVE_ACCOUNT_ID }}
        BRIGHTCOVE_CLIENT_ID: ${{ secrets.BRIGHTCOVE_CLIENT_ID }}
        BRIGHTCOVE_CLIENT_SECRET: ${{ secrets.BRIGHTCOVE_CLIENT_SECRET }}
