name: Linting

env:
  NODE_VERSION: "20"
  NODE_CACHE: "${{ github.workspace }}/node_modules_cache"

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - '[0-9].[0-9x]*' # Version branches: 4.x.x, 4.1.x, 5.x
      - code-improvement # todo remove before merging into develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set standard 10up cache directories
      run: |
        sudo npm config set cache "${{ env.NODE_CACHE }}" --global

    - name: Prepare npm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.NODE_CACHE }}
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ env.NODE_VERSION }}-

    - name: "install node v${{ env.NODE_VERSION }}"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm ci
      run: npm ci

    - name: es lint
      run: npm run lint-js

  phpcs:
    name: PHP Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: cs2pr

      - name: composer install
        run: composer install

      - name: PHPCS check
        run: "./vendor/bin/phpcs . -q --report=checkstyle --warning-severity=6 --runtime-set testVersion ${{ matrix.php }}- | cs2pr"
