name: Linting

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - code-improvement # todo remove before merging into develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v18
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - name: npm install
      run: npm install
    - name: eslint
      run: npm run lint-js

  phpcs:
    name: PHP Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: composer install
        run: composer install

      - name: PHPCS check
        run: composer run lint
